### ISSUE TITLE
buttonevent wrong description

### ISSUE THREAD

**Issue by haldi4803** [chromoxdor/easyfetch#1]
Hi,
Your manual states:

There are two options to generate a button tile:

    Name the first value of a Task "btnState" (a button whose color is dependent of the btnState 0=no color 1=blue) or “btnStateC” (this button is independent from its state always blue) 
https://user-images.githubusercontent.com/33860956/159255555-d7caea8e-4913-4a4b-98b7-f9a83e5c4f3c.png
button simple (the device here is a sonoff s20 and since we do not need the first button, since its the hardwarebutton, on our dahboard we can hide it with the "XX" option. the second button is the actual relay so the state changes depending on the gpio state)

    The rule for it:

      On buttonevent do
       gpiotoggle,12
      endon
     
According to the Image you have Switch named Button with the Value btnState.
But as it seems that doesn't create a "Buttonevent" but a "btnState" event.

I've tried it myself with a generic dummy device dButtons and a Open State.
![image](https://user-images.githubusercontent.com/17104473/200661753-aade3a3e-cf83-49af-a217-da5896e23778.png)

had to make a rule for "openevent" 

'''
31534: WD   : Uptime 1 ConnectFailures 0 FreeMem 24000 WiFiStatus WL_CONNECTED 3 ESPeasy internal wifi status: Conn. IP Init
35318: EVENT: Tor#torstatus=0
39505: HTTP: event,OpenEvent
39558: EVENT: openevent
39567: ACT  : pulse,4,1,800
40369: GPIO : port 4. Pulse set for 800 ms
40734: EVENT: Tor#torstatus=0
57653: EVENT: Tor#torstatus=1
'''

P.S
This is awesome! Thanks a lot for the simple UI with Button functionality.
pretty cool for a Password protected Config Menu that is easily accessible for anyone with the link and one button.

**Comment by chromoxdor** [comment]
I am happy to see, that somebody else is using this (i thought i am the only one 🙂).
Thanks for your input....

> But as it seems that doesn't create a "Buttonevent" but a "btnState" event.

Easyfetch always creates event-names with the scheme "Taskname" + 'event'  unless you use the special options like dbuttons or slider which are based on dummy devices. 
In general you can say, the event-name consists of the name you see in the upper left of a buttontile + 'event


<img width="337" alt="Bildschirmfoto 2022-11-09 um 09 17 36" src="https://user-images.githubusercontent.com/33860956/200777227-f3b1134f-cac6-4efb-bb6a-9e2a96108ae2.png">
<img width="484" alt="Bildschirmfoto 2022-11-09 um 09 17 16" src="https://user-images.githubusercontent.com/33860956/200777308-7a879925-3db9-4788-bdcf-6116161275c4.png">
