### ISSUE TITLE
Wrapper gets wrapped when present as index.htm.gz

### ISSUE THREAD

**Issue by TD-er** [chromoxdor/easyfetch#3]
See screenshot:

![image](https://user-images.githubusercontent.com/3751318/200829558-dffeb24e-fc1f-4502-8acd-7fada4cbaeb3.png)

Steps to reproduce:
- Save easyfetch as index.htm.gz
- Click on "home" icon
- Click in ESPEasy UI on "Main"
- [optional] Click on "home" icon

**Comment by chromoxdor** [comment]
I know... 😁
What do you expect should happen? 
Workaround: You could give the index.htm another name

**Comment by TD-er** [comment]
I can make a setting in ESPEasy to show easyfetch.htm.gz as root page?
This way one can toggle what will be shown.

Right now, with easyfetch stored as index.htm, it is impossible to see the root page of the ESPEasy UI.

What do you think of that?

**Comment by chromoxdor** [comment]
That is a marvelous idea!
This would also fix the reboot-button issue which doesn’t work with custom index.htm.

**Comment by TD-er** [comment]
Hmm I wanted to implement it as a single checkbox, but allowing it for any kind of htm file may require to match some specific htm file name.

what about `index_.htm` ? or `indexalt.htm` ?

**Comment by chromoxdor** [comment]
indexalt.htm is fine i guess

**Comment by haldi4803** [comment]
![image](https://user-images.githubusercontent.com/17104473/200887775-3fc405d0-1ad5-4ce8-88b7-08194c203c61.png)
^^

**Comment by chromoxdor** [comment]
To that day nothing changed regarding that issue. (there seems to be no solution)
This is still the way to go:
> Workaround: You could give the index.htm another name

I´ll close this issue now...
