### ISSUE TITLE
Scrollbar?

### ISSUE THREAD

**Issue by haldi4803** [chromoxdor/easyfetch#4]
Question.
Why are there Scrollbars no matter what Size the window is?
![image](https://user-images.githubusercontent.com/17104473/200845843-fc1345a0-5484-4b73-8549-e0bb3c24a04e.png)

Even on Mobile pages.
![image](https://user-images.githubusercontent.com/17104473/200846005-92c78d1d-457d-456e-8160-4ea502feb8cf.png)

**Comment by chromoxdor** [comment]
[index.htm.gz](https://github.com/chromoxdor/easyfetch/files/9972005/index.htm.gz)
can you test this and see if the scrollbars still there?

**Comment by chromoxdor** [comment]
I used a containerheight of 101vh to make the page on my iphone kind of fullscreen.
And on my mac the scrollbars are hidden when not in use so i never experienced this issue..

**Comment by haldi4803** [comment]
They are gone!
![image](https://user-images.githubusercontent.com/17104473/200887554-11510f6a-05d5-49f3-9f52-c5635ecf81c4.png)
