### ISSUE TITLE
Question, to vSlider

### ISSUE THREAD

**Issue by Nemo135** [chromoxdor/easyfetch#7]
hello, 
is it possible to influence the behavior of the vSlider? I'm specifically concerned with the behavior that occurred in the last 1/6. I would like a slider that doesn't switch. 
Greetings Marco

**Comment by chromoxdor** [comment]
Hi,
i never used the "feature"  myself either and thought about removing it on day. Maybe today is this day :)

**Comment by chromoxdor** [comment]
Ok. I decided to leave the "switch"-behavior in the code and make it optional.
To regain "switch"-behavior in slider a "Sw" needs do be added to "vSlider" or "nvSlider"
e.g.: "vSliderSw"

Let me know if it works for you...

**Comment by Nemo135** [comment]
Hi, yes it works fine for me now. 
Thank you !
Greeting, Marco
